controller:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  kind: Deployment
  replicaCount: 1
  updateStrategy:
    type: Recreate
  service:
    type: ClusterIP
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
  ingressClassResource:
    name: nginx
    default: false
    controllerValue: "k8s.io/ingress-nginx"
  admissionWebhooks:
    enabled: true
