nginx_user: www-data

nginx_worker_processes: auto
nginx_worker_connections: 2048

# Network
nginx_host: 0.0.0.0
nginx_port: 443

# Uploads
nginx_client_max_body_size: 50m

# TLS
nginx_ssl_protocols:
  - TLSv1.2
  - TLSv1.3

nginx_ssl_certificate: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
nginx_ssl_certificate_key: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"

nginx_ssl_session_cache: "shared:SSL:10m"
nginx_ssl_session_timeout: "10m"
nginx_ssl_session_tickets: false

# Web
nginx_web_root: "/var/www/{{ app_name }}-web/current"
nginx_files_root: "/var/lib/{{ app_name }}/files"
