image:
  repository: ghcr.io/kroshhaker2/kr-web
  tag: "1.5.0"
  pullPolicy: IfNotPresent

replicaCount: 2

ingress:
  host: kr.kroshhaker.dev
  tlsSecretName: kr-web-tls
  clusterIssuer: letsencrypt-prod

api_url: "https://api.kr.kroshhaker.dev/api/v1"