image:
  repository: ghcr.io/kroshhaker2/kr-web
  tag: "1.0.2"
  pullPolicy: IfNotPresent

replicaCount: 2

ingress:
  host: kr.kroshhaker.dev
  tlsSecretName: kr-web-tls
  clusterIssuer: letsencrypt-prod
