server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.kr.kroshhaker.dev
    tls:
      - secretName: argocd-tls
        hosts:
          - argocd.kr.kroshhaker.dev
crds:
  install: true
  keep: true
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true

global:
  domain: argocd.kr.kroshhaker.dev
