all:
  hosts:
    server1:
      ansible_host: 2.26.50.120
      ansible_user: root
      ansible_port: 22
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
  children:
    k8s_nodes:
      hosts:
        server1:
    k8s_control_plane:
      hosts:
        server1:
        