---
- name: Ensure administrative user exists and is in sudo group
  ansible.builtin.user:
    name: "{{ admin_user }}"
    shell: "{{ admin_user_shell }}"
    groups: "{{ admin_user_groups }}"
    append: true
    create_home: "{{ admin_user_create_home }}"
    state: present
  register: admin_user_result


- name: Deploy SSH public key for administrative user
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_user_ssh_public_key }}"
    state: present
    exclusive: true
