certbot_email: admin@{{ domain }}

certbot_domains:
  - "{{ domain }}"

certbot_cloudflare_credentials: /etc/letsencrypt/cloudflare.ini

certbot_propagation_seconds: 30

certbot_renew_schedule: "*-*-* 03:00:00"
