apiVersion: apps/v1
kind: Deployment
metadata:
  name: kr-server
  labels:
    app: kr-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kr-server
  template:
    metadata:
      labels:
        app: kr-server
    spec:
      containers:
        - name: kr-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-app-credentials
                  key: endpoint
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-app-credentials
                  key: access-key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-app-credentials
                  key: secret-key
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: minio-app-credentials
                  key: bucket
            - name: PORT
              value: "{{ .Values.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.secretKey }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
