apiVersion: apps/v1
kind: Deployment
metadata:
  name: kr-server
  labels:
    app: kr-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kr-server
  template:
    metadata:
      labels:
        app: kr-server
    spec:
      containers:
        - name: kr-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.port }}"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.secretKey }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}