apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp-rbac
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kroshha/kr-infr.git
    targetRevision: main
    path: k8s-manifests/headlamp
    directory:
      include: 'rbac.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true