apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: kr-postgres
  namespace: kr
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: kr
      owner: kr