image:
  repository: ghcr.io/kroshhaker2/kr-server
  tag: "1.2.4"
  pullPolicy: IfNotPresent

replicaCount: 3

port: 3000

env:
  NODE_ENV: "production"
  CORS_ORIGINS: "https://kr.kroshhaker.dev"
  STORAGE_URL: "https://s3.kr.kroshhaker.dev"

ingress:
  host: api.kr.kroshhaker.dev
  tlsSecretName: kr-server-tls
  clusterIssuer: letsencrypt-prod

database:
  secretName: kr-postgres-app
  secretKey: uri

migrate:
  enabled: true